FROM ubuntu:latest

WORKDIR /app

COPY database.sh .

RUN apt-get update && apt-get install -y xinetd uuid-runtime sqlite3

COPY xinetd.conf /etc/xinetd.conf
COPY servidor-service1 /etc/xinetd.d/servidor-service1

RUN chmod +x ./database.sh
