version: '3.8'
services:
  load-balancer:
  # xinetd_service:
    # image: nginx:latest
    build: .
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    restart: always
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
