version: '3.8'
services:
  load-balancer:
  # xinetd_service:
    # image: nginx:latest
    build: .
    ports:
      - "9999:9999"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

